### ISSUE TITLE
Extension methods are generating incorrect code

### ISSUE THREAD

**Issue by jothompson-prismhr** [zompinc/sync-method-generator#13]
Extension methods do not appear to work correctly. It does not rearrange the order of the method call to call the extension directly, but does insert the global namespace in the middle.

**Comment by jothompson-prismhr** [comment]
This may only be if we are using the null access modifier like `?.ExtensionMethod(...`

**Comment by virzak** [comment]
Can you provide an example? Can't reproduce.

**Comment by jothompson-prismhr** [comment]
I put the following in a shared project:

```cs
using Extensions;

namespace Extensions
{
    public static partial class Extensions
    {
        [Zomp.SyncMethodGenerator.CreateSyncVersion]
        public static async Task<string?> AddSomethingAsync(this string s)
        {
            if (string.IsNullOrEmpty(s)) {
                return "";
            }
            var t = await GetSomethingAsync();

            return $"{s}{t}";
        }

        private static string GetSomething()
        {
            return "Something";
        }

        private static Task<string> GetSomethingAsync()
        {
            return Task.FromResult("Something");
        }
    }
}
```

And the following in a project that references that project:

```cs
using Extensions;

public partial class Test
{
    [Zomp.SyncMethodGenerator.CreateSyncVersion]
    public async Task<string> GetStringAsync(string s)
    {
        return await s?.AddSomethingAsync();
    }
}
```

And it is showing this as the generated code:

```cs
// <auto-generated/>
#nullable enable
public partial class Test
{
    public string GetString(string s)
    {
        return s?.AddSomethingAsync();
    }
}
```

If I remove the `?` then it generates the following:

```cs
// <auto-generated/>
#nullable enable
public partial class Test
{
    public string GetString(string s)
    {
        return global::Extensions.Extensions.AddSomething(s);
    }
}
```

**Comment by jothompson-prismhr** [comment]
This also appears to be an issue if it isn't an async method:

```cs
using Extensions;
public partial class Test
{
    [Zomp.SyncMethodGenerator.CreateSyncVersion]
    public Task<string> GetStringAsync(string s)
    {
        return Task.FromResult(s?.AddSomething());
    }
}
```

Generates:

```cs
// <auto-generated/>
#nullable enable
public partial class Test
{
    public string GetString(string s)
    {
        return s?.AddSomething();
    }
}
```

**Comment by jothompson-prismhr** [comment]
Yeah I think that would work. Might get complicated if multiple are chained together though to keep it to only one call for each method. What would be the pros and cons of having a using in the generated code for extension method namespaces?

**Comment by virzak** [comment]
That's a good question. I imagine `using`s are sometimes avoided in source generators to avoid some namespace collisions, but this is just me guessing.

These prominent libraries avoid `using`s:

- [ComminutyToolkit.Mvvm](https://github.com/CommunityToolkit/dotnet)
- [.NET regular expression](https://learn.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-source-generators)

But these ones don't:

- [CSWin32](https://github.com/microsoft/CsWin32)
- [Fody.PropertyChanged](https://github.com/Fody/PropertyChanged)

I went with the first group intuitively, but perhaps that just complicated things.

**Comment by Sergio0694** [comment]
I've written a detailed answer for this in https://github.com/dotnet/runtime/pull/94428#issuecomment-1796294871 and other comments in that conversation. The TLDR is that it's not safe to emit `using` directives when generating code inside a namespace that's defined by the user. So basically a simple rule of thumb is the following:
- If you're generating code in a user defined namespace, always use global fully qualified type names
- If you're generating code in a "reserved" generator namespace (eg. "MyLibrary.Generated"), you can emit `using` directives **inside** the namespace declarations (don't emit them outside, or there might be conflicts in rare cases), and then use simple names within that namespace scope.

**Comment by jothompson-prismhr** [comment]
So to change something like `var x = s?.First()?.Second()` could it do this?

```cs
var x = s switch {
    type_of_s y => global::Namespace.Of.First(x) switch {
        type_of_first z => global::Namespace.Of.Second(y),
        _ => default(type_of_second),
    },
    _ => default(type_of_second),
};
```

And you could just keep nesting switch expressions and generating the names for the intermediate variables. Or do we know what other projects do when translating the null propagation?

**Comment by virzak** [comment]
Yeah, except I'll probably avoid the switch statement for cases when LangVersion is low. Nesting will be fun.

**Comment by virzak** [comment]
@jothompson-prismhr Version [1.2.3](https://www.nuget.org/packages/Zomp.SyncMethodGenerator/1.2.3) is not available and fixes this issue.

The implementation currently assumes that nullable reference type is turned on. It uses inline `Func<>` for chained or complex expressions and simple if statements. I like the `switch` idea, so if the lang version supports it, the source generator could generate friendlier code using switch.

Thanks for all the issues and I hope you find the SG useful.
