### ISSUE TITLE
ConfigureAwait(false) helper support?

### ISSUE THREAD

**Issue by lsoft** [zompinc/sync-method-generator#24]
Hello!

This is a very useful generator, thank you for this work!

I would ask if I have a helper like this:

```C#
    public static class AwaitHelper
    {
        public static ConfiguredValueTaskAwaitable<T> Caf<T>(this ValueTask<T> task)
        {
            return task.ConfigureAwait(false);
        }

        public static ConfiguredTaskAwaitable<T> Caf<T>(
            this Task<T> task
            )
        {
            return task.ConfigureAwait(false);
        }

        public static ConfiguredTaskAwaitable Caf(
            this Task task
            )
        {
            return task.ConfigureAwait(false);
        }
    }
```
and the following async method:

```C#
static async Task WriteAsync(ReadOnlyMemory<byte> buffer, Stream stream, CancellationToken ct)
    => await stream.WriteAsync(buffer, ct).Caf();
```

will this generator remove `Caf()` invocation? if no, any settings to enable this behaviour? Such helpers are widespread in random codebases...

ps. probably, you want to append the section `A list of changes applied to the new synchronized method`  with the note, that the generator will remove the suffix `Async` from the name of async method (not from the internal invocations). :)

**Comment by lsoft** [comment]
@virzak  I have prototyped this here: https://github.com/lsoft/sync-method-generator/commit/cbd48ae9da86ae3f7072b723865501507936ef3e

I choose to add a new attribute and mark the methods which invocations must be removed when sync method is generating. Not sure that my changes are of good quality. And I pretty sure we need additional tests for this feature.

But, in general, could you take a look and give me your feedback? will you accept such PR?

**Comment by virzak** [comment]
@lsoft,

Thanks for the effort. I should have let you know that I was looking at this last night and I was almost done on my side too.

We don't need to introduce another attribute here, because when the invocation has a return type of Configured(Value)TaskAwaitable, it should be dropped automatically. Currently we check for "ConfigureAwait" method name and going by return type should be a better approach.

This fix should be available later on today.

**Comment by lsoft** [comment]
@virzak your approach is viable, but is dangerous a bit. Imagine that one writes the following method:

```C#
   public static class AwaitHelper
    {
        public static ConfiguredTaskAwaitable Caf(
            this Task task
            )
        {
            Console.WriteLine("side effect");
            return task.ConfigureAwait(false);
        }
    }
```

the side effect will be lost if ISG removed `Caf` because of return type. We are in safe if we will remove only pure `ConfigureAwait`-functions, but I don't think it is feasible (and make sense) to determine such pureness in the code. I would prefer to delegate this responsibility to the programmer by adding an attribute or any other way.

Nevertless, this situation is so rare, that you can probably ignore this difficulty. I'm personally fine with it.

**Comment by virzak** [comment]
Also with the example described above, you can't really skip `[RemoveAsyncInvocation]` anyways. Any method that returns a `Task` would now have to return `void` and you can't pass void to a helper method.
