### ISSUE TITLE
The failure of the generator if async method calls a method with `params` keyword.

### ISSUE THREAD

**Issue by lsoft** [zompinc/sync-method-generator#25]
The ISG suffers from exception inside a `GetIndices` for the following unit test:

```C#
    [Fact]
    public Task ParamsTest() => $$"""
public partial class Subject
{
    [CreateSyncVersion]
    public async Task<byte[]> ReceiveBytesAsync()
    {
        await Task.Delay(1);

        var b0 = new byte[1];
        var b1 = new byte[1];
        return Helpers.HelperMethod1(b0, b1);
        //return Helpers.HelperMethod2(b0, b1); <-- using this instead of HelperMethod1 is OK
    }
}

internal static class Helpers
{
    internal static byte[] HelperMethod2(byte[] b0, byte[] b1)
    {
        return null!;
    }

    internal static byte[] HelperMethod1(params byte[][] partials)
    {
        return null!;
    }

}
""".Verify(false, true, sourceType: SourceType.Full);
```

I looked at the code and feel no luck for me to fix this. Could anyone take a look?

(to be honest it is not clear why we need to deep inside a non-async nodes and analyze its arguments? why not to pass it as is?)

**Comment by virzak** [comment]
Thanks for a perfect test case. If I remember correctly, invocation arguments are analyzed in order to exclude `CancellationToken` and `IProgress` stuff. Sometimes they are out of order if previous arguments are optional.

And yes, `params` was never handled, so great catch!
