### ISSUE TITLE
await Task.Delay(...); should be converted into Thread.Sleep

### ISSUE THREAD

**Issue by lsoft** [zompinc/sync-method-generator#28]
Hi!

I found that `await Task.Delay(...)` is lost (of course) in sync sibling. Let me suggest that this should be converted into `Thread.Sleep()`.

The real situation: a some resource pool. Async method tried to get the resource, if the resource is locked (or missing), then the method waits (`await Task.Delay(...);`) for a timeout, checks again and fails if the resource is still not here. A sync sibling of the method should use `Thread.Sleep`.

(there are `int` and `TimeSpan` overloads, and (as usual) `CancellationToken` should be dropped)

ps. I'm not sure that `Thread.Sleep` is the best option here and I open for any ideas. May be we want to have a new ISG setting `what to produce instead of Task.Delay`?

**Comment by virzak** [comment]
Thread.Sleep is a good option. Any time a default option doesn't fit `SYNC_ONLY` and `!SYNC_ONLY` are available.

**Comment by lsoft** [comment]
@virzak looks like there is a bug. Please take a look at the following screenshot, I take it from 1.2.13:

![image](https://github.com/zompinc/sync-method-generator/assets/5988558/7adef6a4-9a21-483d-924b-11ed1a7bccf2)

I suspect that `Caf` (or `ConfigureAwait` is reason of `Task.Delay` disappearance.

**Comment by virzak** [comment]
Yep. Looks like that second invocation drops the entire statement.

**Comment by virzak** [comment]
All should be good in version 1.2.16
