### ISSUE TITLE
Convert types inside `nameof()` to fully qualified

### ISSUE THREAD

**Issue by virzak** [zompinc/sync-method-generator#31]
First mentioned here #30

This issue is more complex than is seems, unless I'm missing something. It may also slow down the compilation.
In the meantime `global::MyNS.MyType` should be used.

It is impossible to get a symbol inside `nameof`. The best thing is to get the string inside:

Currently my best solution is to provide AsyncToSyncRewriter with (or retrieve it on demand using `semanticModel.Compilation`)
- Assembly locations names available [ExternalReferences](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.compilation.externalreferences?view=roslyn-dotnet-4.7.0#microsoft-codeanalysis-compilation-externalreferences) from CSharpCompilation
- Global namespaces from all [SyntaxTrees](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.compilation.syntaxtrees)

Here is a condition to look for:
```cs
node.Expression is IdentifierNameSyntax { Identifier.ValueText: "nameof" }
&& semanticModel.GetConstantValue(node) is { HasValue: true, Value: string { } nameOfContent
```
as described [here](https://stackoverflow.com/a/39331999).

When condition is met check if it doesn't start with `global::` and if so, bail out.

Retrieve all types in the Assemblies that match the required namespace.

Grab all usings from the current compilation: 

```cs
(CompilationUnitSyntax)node.SyntaxTree.GetRoot().Usings;
```
and combine them with global usings into `includedNamespaces`

Get all type definitions for available namepaces:
```cs
var types = assemblyPaths
    .SelectMany(a => Mono.Cecil.AssemblyDefinition.ReadAssembly(a).Modules[0].Types
        .Where(t => includedNamespaces.Contains(t.Namespace)));
```

Compare `nameofContent` to all available types and replace if there's a single match. Test a case when `nameofContent` contains partial namespace hierarchy.

**Comment by lsoft** [comment]
@virzak 

> It is impossible to get a symbol inside nameof. 

could you add details here, please?

if I understand the problem correctly, there is a difficulty if the symbol is a method name ( https://github.com/dotnet/roslyn/issues/23902#issuecomment-356050811 ), but with type name I see the symbol in this way:

1. create unit test
```C#
    [Fact]
    public Task NameofMethod() => $$"""
namespace NsFour
{
    public partial class MultipleNamespaces
    {
        [CreateSyncVersion]
        async Task<string> EmptyAsync()
        {
            return nameof(EmptyAsync);
        }
    }
}
""".Verify(false, true, sourceType: SourceType.Full);
```

2. set a breakpoint at first line in the method `public override SyntaxNode? VisitMethodDeclaration(MethodDeclarationSyntax node)` (rewriter).
3. start unit test in debug mode
4. wait for the breakpoint has fired.
5. press shift+f9 to see evaluator and paste the following `semanticModel.GetSymbolInfo( (node.DescendantNodes().ToList()[12] as ArgumentSyntax).Expression ).Symbol.Name`

I see 
![image](https://github.com/zompinc/sync-method-generator/assets/5988558/a78257dd-3bf9-4469-b11b-917ffd1f33ad)

in the case of nameof-method we will need to perform additional magic, as I understand today...

**Comment by virzak** [comment]
Your test case is for EmptyAsync - a method.

Try this:

```cs
[Fact]
public Task HandleNameOf()
    => "_ = nameof(Stream);"
    .Verify(sourceType: SourceType.MethodBody);
```

**Comment by lsoft** [comment]
all three unit tests are OK for me

```C#
    [Fact]
    public Task NameofMethod() => $$"""
using System.IO;
namespace NsFour
{
    public partial class MultipleNamespaces
    {
        [CreateSyncVersion]
        async Task<string> EmptyAsync()
        {
            return nameof(Stream);
        }
    }
}
""".Verify(false, true, sourceType: SourceType.Full);

    [Fact]
    public Task NameofMethod2() => $$"""
            return nameof(Stream);
""".Verify(false, true, sourceType: SourceType.MethodBody);

    [Fact]
    public Task NameofMethod3() => $$"""
            _ = nameof(Stream);
""".Verify(false, true, sourceType: SourceType.MethodBody);

```

I checked `semanticModel.GetSymbolInfo( (node.DescendantNodes().ToList()[12] as ArgumentSyntax).Expression ).Symbol.Name`

(the last one is required index 14 instead of 12)

could you confirm this?

**Comment by virzak** [comment]
Wow!!! You're right.

Will fix tomorrow.
