### ISSUE TITLE
Should the Zomp.SyncMethodGenerator NuGet package specify what its license is?

### ISSUE THREAD

**Issue by Numpsy** [zompinc/sync-method-generator#53]
Hi,

An observation whilst looking at https://github.com/Zeugma440/atldotnet/pull/251#issuecomment-1943704517 - the LICENSE file in the git repo here says that the license is MIT, but the NuGet package doesn't seem to contain a license field:

![image](https://github.com/zompinc/sync-method-generator/assets/1178570/90ca4998-dbf3-46c8-8192-7223c20881d6)

should it?

(Context: there are tools at work that like to complain when packages don't explicitly specify a license)

**Comment by virzak** [comment]
Will specify. Thanks.
