### ISSUE TITLE
IProgress still passed as parameter in the generated sync code

### ISSUE THREAD

**Issue by Zeugma440** [zompinc/sync-method-generator#6]
Hi there,

What you created seems to be exactly what I need to eradicate duplicated code while keeping good performance 😄 

However, the tests I've done came to this showstopper :

**Async code : StreamUtil (callee)**
```cs
public static async Task LengthenStreamAsync(Stream s, long oldIndex, uint delta, IProgress<float> progress = null, bool fillZeroes = false) { ... }
```

**Async code (caller)**
```cs
IProgress<float> progress = initIProgress(zoneRegions);
...
await StreamUtils.LengthenStreamAsync(writer, tagEndOffset, deltaBytes, (null == someVar) ? progress : null);
```
Caller passes an `IProgress` to the async `StreamUtil` method

***

**Generated sync code : StreamUtil (callee)**
```cs
public static void LengthenStream(global::System.IO.Stream s, long oldIndex, uint delta, bool fillZeroes = false) { ... }
```
The async `StreamUtil` signature is rewritten without the `IProgress` parameter => OK, works as designed

**Generated sync code (caller)**
```cs
IProgress<float> progress = initIProgress(zoneRegions);
...
global::ATL.StreamUtils.LengthenStream(writer, tagEndOffset, deltaBytes, (null == buffer) ? progress : null);
```
The caller still uses an `IProgress` as a 3rd argument => KO, it should have been removed

**Comment by virzak** [comment]
@Zeugma440, yes this is exactly what you need 😄.

Your issue is fixed in version 1.0.2.

Thanks for reporting, happy to fix another if you come across one.

**Comment by Zeugma440** [comment]
Thanks a bunch for the quick answer 👍 

I just updated but the post-build situation is super weird : the generated .CS source code is identical to what I had yesterday with v1.0.1 of the code generator, but I can see the build errors and warnings have evolved (and are coherent with what I expected from this fix).

Is this a Visual Studio issue ? To your knowledge, is there some kind of "generated code cache" that should be cleared ?

Thanks~

**Comment by virzak** [comment]
Yeah, Visual Studio is weird like that. It helps to restart it, but I'm sure you have already done that. `dotnet build` is a lot more reliable. There could also still be an issue with source generator. If you share the branch or PR where you are integrating it, I'd be able to tell.

**Comment by virzak** [comment]
Version 1.0.3 resolved this issue for other expressions, such as method calls, array access, new Progress<T>(), etc

**Comment by Zeugma440** [comment]
> Yeah, Visual Studio is weird like that. It helps to restart it, but I'm sure you have already done that. `dotnet build` is a lot more reliable. There could also still be an issue with source generator. If you share the branch or PR where you are integrating it, I'd be able to tell.

Restarting the computer itself fixed it for me. Thanks for your reply :)

> Version 1.0.3 resolved this issue for other expressions, such as method calls, array access, new Progress(), etc

Indeed, it's better now but there's still one parasite line in the generated code that should be removed

```cs
if (null == var1 && var2 != null && !object1.IsReadonly) iProgress = incrementProgress();
```
^ the sole purpose of that line is to give a new value to iProgress (of type IProgress<float>). I should be removed too.

**Comment by Zeugma440** [comment]
PS : Don't hesitate if you prefer me to open a new issue instead of talking over a closed one ;)
