### ISSUE TITLE
Incorrect removal of `Span` property call

### ISSUE THREAD

**Issue by skarllot** [zompinc/sync-method-generator#60]
When a code has a `Memory` variable and call `Span` for passing as parameter, the call is removed

```csharp
var encoder = TextEncoding.GetEncoder();
using var bufferOwner = MemoryPool<byte>.Shared.Rent();
var sharedBuffer = bufferOwner.Memory;

encoder.Convert(
    value.AsSpan(charsConverted),
    sharedBuffer.Span, // <-- generate as: sharedBuffer,
    false,
    out int charsUsed,
    out int bytesUsed,
    out _);
```

**Comment by virzak** [comment]
There are 2 options here:

1. var sharedBuffer = bufferOwner.Memory.Span
2. sharedBuffer.Span (As you suggested)

I'm leaning to 1. to eliminate memory from a sync method altogether

What are your thoughts?

**Comment by skarllot** [comment]
I do prefer the first option too, because I think that it more performant when accessed in a loop. In fact, my original code is like that.
