### ISSUE TITLE
Invalid operation at build-time : "AbstractKeyword is not supported"

### ISSUE THREAD

**Issue by Zeugma440** [zompinc/sync-method-generator#7]
I've generalized the `[Zomp.SyncMethodGenerator.CreateSyncVersion]` annotation to all eligible parts of my project.

Now I'm getting that line in the build log, and no sync code is generated anymore :

`
CSC : warning CS8785: Generator 'SyncMethodSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidOperationException' with message 'AbstractKeyword is not supported'
`

Does that mean your library doesn't handle abstract classes? Is that definitive, or is there a possible fix/workaround?

Thanks in advance for your support

**Comment by virzak** [comment]
I actually fixed this on the weekend, but didn't push. Thanks for catching it. Excited about this library being integrated into your code base!

Version 1.0.11 fixes this.

**Comment by Zeugma440** [comment]
It works now \o/   Thanks for the quick response
