### ISSUE TITLE
Primtive type array will fail to compile

### ISSUE THREAD

**Issue by persn** [zompinc/sync-method-generator#71]
Consider the following cases

```csharp
[Zomp.SyncMethodGenerator.CreateSyncVersion]
public async Task Foo1Async(int bar) => await Task.Delay(100);

[Zomp.SyncMethodGenerator.CreateSyncVersion]
public async Task Foo2Async(Int32 bar) => await Task.Delay(100);

[Zomp.SyncMethodGenerator.CreateSyncVersion]
public async Task Foo3Async(int[] bar) => await Task.Delay(100);

[Zomp.SyncMethodGenerator.CreateSyncVersion]
public async Task Foo4Async(Int32[] bar) => await Task.Delay(100);
```

1, 2, 3 works, but `Foo4Async` will fail to compile because it cannot find Int32 in the following generated code

```csharp
public void Foo4(Int32[] bar) => global::System.Threading.Thread.Sleep(100);
```

`Int32` needs to be qualified with a `System.` to be used, alternatively `Int32` works in `Foo2Async` because it gets transformed to the syntax keyword `int`.

Please note that if you have `<ImplicitUsings>enable</ImplicitUsings>` in your csproj, props or targets you will not be able to reproduce this, because then the System namespace will be implicit.

**Comment by virzak** [comment]
@persn. thanks for reporting.

Version 1.3.39 will be available shortly with the fix.

**Comment by persn** [comment]
Looks like it's working, thanks
