### ISSUE TITLE
?. operator with extension method doesn't respect OmitNullableDirective

### ISSUE THREAD

**Issue by persn** [zompinc/sync-method-generator#73]
The following code

```csharp
    internal partial class Class14
    {
        [Zomp.SyncMethodGenerator.CreateSyncVersion(OmitNullableDirective = true)]
        public async Task FooAsync()
        {
            await Task.Delay(100);

            var bar = Bar.Create();
            _ = bar?.DoSometing();
        }

        public Bar Create() => new Bar();
    }

    internal static class BarExtension
    {
        public static Bar DoSometing(this Bar bar) => bar;
    }

    internal class Bar
    {
        public static Bar Create() => new Bar();
    }
```

Generates the following

```csharp
        public void Foo()
        {
            global::System.Threading.Thread.Sleep(100);

            var bar = global::ClassLibrary1.Bar.Create();
            _ = ((object?)bar == null?(global::ClassLibrary1.Bar?)null: global::ClassLibrary1.BarExtension.DoSometing(bar));
        }
```

Which uses nullable reference types despite that I specified that I didn't want them

On another note, extension methods seems generally unstable, if I do this instead `_ = Bar.Create()?.DoSometing();`, the generator will crash with `failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'Syntax node is not within syntax tree'.`.

**Comment by virzak** [comment]
Both issues are related to `OmitNullableDirective`. This is a fairly new addition, so hasn't been tested thoroughly. Looking into it. Might not be as fast, since I'm on vacation.

**Comment by virzak** [comment]
Actually only one of the issues is related to `OmitNullableDirective`

**Comment by virzak** [comment]
Version 1.3.43 has the fixes.

**Comment by persn** [comment]
It appears to be fixed 👍
