### ISSUE TITLE
Type issues with certain syntaxes

### ISSUE THREAD

**Issue by Zeugma440** [zompinc/sync-method-generator#8]
Code generation seems to forget to type certain variables, leading to build issues.

So far I have identified these two cases

1/ Try / catch block

```cs
try 
{
    ...
    try
    {
    ...
     }
     finally
     {
     ...
     }
    ...
}
catch (Exception e) // <== issue here in generated code :  "Error	CS0246	The type or namespace name 'Exception' could not be found (are you missing a using directive or an assembly reference?)"
{
...
}
```

I have no workaround for that one

2/ foreach block

```cs
foreach (MyClass element in elementsList) // <== issue here as well; can be circumvented by using "var"
{
...
}
```

Could you investigate that please ? :) 🙏

**Comment by virzak** [comment]
Got it.

Will fix. In the meantime see if you can add `<Using Include="MyNamecspace.MyClass" />` into the project file.
Alternatively try something like `catch (global::System.Exception e)`

**Comment by Zeugma440** [comment]
> Alternatively try something like catch (global::System.Exception e)

Dang, I should've thought about that 🤦  Thanks !

**Comment by virzak** [comment]
1.0.12 is available with the fix

**Comment by Zeugma440** [comment]
Works fine, thanks for the quick answer as always ;)

Now this is it -- I finally got rid of all duplicated sync/async methods on my project ! 

That's one hell of a library you have here 💪

**Comment by virzak** [comment]
Thank you so much.

The established solution is: https://www.thereformedprogrammer.net/using-valuetask-to-create-methods-that-can-work-as-sync-or-async/

I didn't know about it when I started this library, but I don't really like it. I also did some adhoc benchmarking and it seems slower too. Have you tried this approach?

**Comment by Zeugma440** [comment]
I didn't know about that approach. I've been keeping both sync and async methods as there was clearly a need for both of them (more about that [here](https://github.com/Zeugma440/atldotnet/wiki/Progress-feedback)). 

Tbh, I've always feared tinkering with advanced .NET tweaks I don't even understand myself :
1/ Wouldn't come out as efficient as calling a good old sync method - and I do need efficiency
2/ Might get hiccups or unwanted behaviour when used in exotics contexts, e.g. Mono or mutithreaded apps

**Comment by virzak** [comment]
So yeah, after doing a proper benchmark, you can save around 20-30% in libraries which don't use long synchronized operations like Stream.Write(). See the issue linked above for discussion. Ultimately, I prefer the source generator too, though I might be biased lol.
