### ISSUE TITLE
Interface's static method support

### ISSUE THREAD

**Issue by lsoft** [zompinc/sync-method-generator#82]
Looks like they are not supported. 

![image](https://github.com/zompinc/sync-method-generator/assets/5988558/3bfbc95d-2009-43ed-ad1f-e7447bad6d63)

```C#
    internal class Program
    {
        static void Main(string[] args)
        {
            IMyInterface.Do();
        }
    }

    //public partial interface IMyInterface
    //{
    //    static void Do()
    //    {
    //    }
    //}

    public partial interface IMyInterface
    {
        [Zomp.SyncMethodGenerator.CreateSyncVersion]
        static async Task DoAsync()
        {
        }
    }
```

Thank you for your work, Victor, we are using your generator with great success!

**Comment by virzak** [comment]
> we are using your generator with great success

Thank you for saying that. Makes me really happy!

The issue is resolved in 1.4.8
