### ISSUE TITLE
does not generate method definition

### ISSUE THREAD

**Issue by ignatandrei** [zompinc/sync-method-generator#9]
Please see attached solution - it does not generate code in the definition for method write ( it is still generating for Haha method)
[src.zip](https://github.com/zompinc/sync-method-generator/files/12257173/src.zip)

**Comment by virzak** [comment]
Thanks Andrei,

Should be available in 1.0.14.

**Comment by ignatandrei** [comment]
Thanks
Added to my list of RSCG, https://ignatandrei.github.io/RSCG_Examples/v2/docs/Zomp

**Comment by virzak** [comment]
Really appreciate that.

The only thing: the name is wrong. Should be Sync Method Generator, not Zomp. And it is not an image generator. This used to be a wrong description some time ago, but is now fixed.

**Comment by ignatandrei** [comment]
Done: https://ignatandrei.github.io/RSCG_Examples/v2/docs/SyncMethodGenerator
